server:
  port: 8081

spring:
  application:
    name: user-center-service

  datasource:
    url: jdbc:mysql://192.168.95.130:3306/user_center?serverTimezone=GMT%2B8&useSSL=false
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.95.130:8848

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

